In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("classic_rock_playlist.csv")
df1.head()

,Artist,Music,Album,Year,Genre,2022,2021,2020,2019,2018,2017,2016,2015
0,The Black Crowes,Remedy,The Southern Harmony and Musical Companion,1992,Southern Rock,500,NaN,324.0,290.0,132.0,64.0,36.0,NaN
1,Asia,Only Time Will Tell,Asia,1982,Progressive Rock,499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Collective Soul,Shine,Hints Allegations and Things Left Unsaid,1993,Alternative Rock,498,NaN,NaN,419.0,485.0,403.0,NaN,NaN
3,Billy Idol,Sweet Sixteen,Whiplash Smile,1986,Rock,497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Collective Soul,December,Collective Soul,1995,Alternative Rock,496,NaN,NaN,NaN,431.0,443.0,NaN,NaN

In [4]:
df1.shape

(500, 13)

In [8]:
df1.groupby('Genre')['Genre'].agg('count')

Genre
A Cappella            1
Acoustic Rock         1
Alternative Metal     1
Alternative Rock     33
Arena Rock            3
                     ..
Symphonic Rock        2
Synth Rock            1
Synthpop              6
Thrash Metal          1
Worldbeat             1
Name: Genre, Length: 61, dtype: int64

In [10]:
df2 = df1.drop(['Music'], axis='columns')
df2.head()

,Artist,Album,Year,Genre,2022,2021,2020,2019,2018,2017,2016,2015
0,The Black Crowes,The Southern Harmony and Musical Companion,1992,Southern Rock,500,NaN,324.0,290.0,132.0,64.0,36.0,NaN
1,Asia,Asia,1982,Progressive Rock,499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Collective Soul,Hints Allegations and Things Left Unsaid,1993,Alternative Rock,498,NaN,NaN,419.0,485.0,403.0,NaN,NaN
3,Billy Idol,Whiplash Smile,1986,Rock,497,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Collective Soul,Collective Soul,1995,Alternative Rock,496,NaN,NaN,NaN,431.0,443.0,NaN,NaN

In [11]:
df2.isnull().sum()

Artist      0
Album       3
Year        0
Genre       0
2022        0
2021      192
2020      261
2019      239
2018      240
2017      240
2016      274
2015      315
dtype: int64

In [15]:
df3 = df2.dropna()
df3.head()

,Artist,Album,Year,Genre,2022,2021,2020,2019,2018,2017,2016,2015
59,Van Halen,Van Halen,1978,Hard Rock,441,409.0,57.0,82.0,148.0,192.0,399.0,340.0
66,Bad Religion,Recipe for Hate,1993,Punk Rock,434,282.0,337.0,201.0,298.0,71.0,197.0,151.0
69,Lynyrd Skynyrd,Pronounced,1973,Southern Rock,431,33.0,21.0,13.0,49.0,17.0,58.0,24.0
87,The Verve,Urban Hymns,1997,Britpop,413,435.0,322.0,180.0,416.0,378.0,391.0,500.0
96,Twisted Sister,Stay Hungry,1984,Hard Rock,404,254.0,346.0,281.0,360.0,221.0,443.0,338.0

In [20]:
df3.isnull().sum()

Artist    0
Album     0
Year      0
Genre     0
2022      0
2021      0
2020      0
2019      0
2018      0
2017      0
2016      0
2015      0
dtype: int64

In [32]:
df3.shape

(94, 12)